name: OBS Build Trigger

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install osc and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip fortune-mod
          pip3 install --upgrade osc

      - name: Configure osc non interattivo
        run: |
          mkdir -p ~/.config/osc
          echo "[general]" > ~/.config/osc/oscrc
          echo "apiurl = https://api.opensuse.org" >> ~/.config/osc/oscrc
          echo "" >> ~/.config/osc/oscrc
          echo "[https://api.opensuse.org]" >> ~/.config/osc/oscrc
          echo "user = ${{ secrets.OBS_USER }}" >> ~/.config/osc/oscrc
          echo "pass = ${{ secrets.OBS_PASS }}" >> ~/.config/osc/oscrc

      - name: Checkout OBS package
        run: |
          osc checkout home:kLeZ-hAcK/linux-madness-fortune

      - name: Copy repo files to OBS package directory
        run: |
          rsync -av --delete ./ linux-madness-fortune/

      - name: Commit and push to OBS
        env:
          OBS_PASS: ${{ secrets.OBS_PASS }}
        run: |
          cd linux-madness-fortune
          osc addremove
          osc commit -m "Build trigger from GitHub Actions"
